In [0]:
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import Sequential
from tensorflow.keras.layers import Flatten, Dense
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split

In [0]:
#Pega csvs de repositorios publico
import requests
url = 'https://raw.githubusercontent.com/laxmimerit/Building-Your-First-ANN-with-TensorFlow-2.0/master/Customer_Churn_Modelling.csv'
res = requests.get(url, allow_redirects=True)
with open('Customer_Churn_Modelling.csv','wb') as file:
    file.write(res.content)
df = pd.read_csv('Customer_Churn_Modelling.csv')

In [0]:
df.head()

RowNumber 
 CustomerId 
 Surname 
 CreditScore 
 Geography 
 Gender 
 Age 
 Tenure 
 Balance 
 NumOfProducts 
 HasCrCard 
 IsActiveMember 
 EstimatedSalary 
 Exited 
 
 
 
 
 0 
 1 
 15634602 
 Hargrave 
 619 
 France 
 Female 
 42 
 2 
 0.00 
 1 
 1 
 1 
 101348.88 
 1 
 
 
 1 
 2 
 15647311 
 Hill 
 608 
 Spain 
 Female 
 41 
 1 
 83807.86 
 1 
 0 
 1 
 112542.58 
 0 
 
 
 2 
 3 
 15619304 
 Onio 
 502 
 France 
 Female 
 42 
 8 
 159660.80 
 3 
 1 
 0 
 113931.57 
 1 
 
 
 3 
 4 
 15701354 
 Boni 
 699 
 France 
 Female 
 39 
 1 
 0.00 
 2 
 0 
 0 
 93826.63 
 0 
 
 
 4 
 5 
 15737888 
 Mitchell 
 850 
 Spain 
 Female 
 43 
 2 
 125510.82 
 1 
 1 
 1 
 79084.10 
 0

In [0]:
X = df.drop(["RowNumber","CustomerId","Surname","Exited"], axis=1)
y = df["Exited"]

In [0]:
X.head()

CreditScore 
 Geography 
 Gender 
 Age 
 Tenure 
 Balance 
 NumOfProducts 
 HasCrCard 
 IsActiveMember 
 EstimatedSalary 
 
 
 
 
 0 
 619 
 France 
 Female 
 42 
 2 
 0.00 
 1 
 1 
 1 
 101348.88 
 
 
 1 
 608 
 Spain 
 Female 
 41 
 1 
 83807.86 
 1 
 0 
 1 
 112542.58 
 
 
 2 
 502 
 France 
 Female 
 42 
 8 
 159660.80 
 3 
 1 
 0 
 113931.57 
 
 
 3 
 699 
 France 
 Female 
 39 
 1 
 0.00 
 2 
 0 
 0 
 93826.63 
 
 
 4 
 850 
 Spain 
 Female 
 43 
 2 
 125510.82 
 1 
 1 
 1 
 79084.10

In [0]:
y.head()

Out[7]: 0    1
1    0
2    1
3    0
4    0
Name: Exited, dtype: int64

In [0]:
from sklearn.preprocessing import LabelEncoder

In [0]:
geo = LabelEncoder()
X["Geography"] = geo.fit_transform(X["Geography"])

In [0]:
X.head()

CreditScore 
 Geography 
 Gender 
 Age 
 Tenure 
 Balance 
 NumOfProducts 
 HasCrCard 
 IsActiveMember 
 EstimatedSalary 
 
 
 
 
 0 
 619 
 0 
 Female 
 42 
 2 
 0.00 
 1 
 1 
 1 
 101348.88 
 
 
 1 
 608 
 2 
 Female 
 41 
 1 
 83807.86 
 1 
 0 
 1 
 112542.58 
 
 
 2 
 502 
 0 
 Female 
 42 
 8 
 159660.80 
 3 
 1 
 0 
 113931.57 
 
 
 3 
 699 
 0 
 Female 
 39 
 1 
 0.00 
 2 
 0 
 0 
 93826.63 
 
 
 4 
 850 
 2 
 Female 
 43 
 2 
 125510.82 
 1 
 1 
 1 
 79084.10

In [0]:
gender = LabelEncoder()
X["Gender"] = gender.fit_transform(X["Gender"])

In [0]:
X = pd.get_dummies(X, drop_first=True, columns=["Geography"])

In [0]:
from sklearn.preprocessing import StandardScaler

In [0]:
X_train, X_test ,y_train,y_test = train_test_split(X, y, test_size=.2, stratify=y)

In [0]:
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [0]:
X_train

Out[19]: array([[ 1.80344346,  0.91324755,  1.53693232, ...,  0.69703307,
        -0.57850497, -0.57600312],
       [-0.28434406,  0.91324755,  0.29611411, ...,  0.01399486,
         1.72859362, -0.57600312],
       [ 0.72355336,  0.91324755,  0.67790433, ...,  0.05078861,
        -0.57850497, -0.57600312],
       ...,
       [ 0.27102799, -1.09499335, -0.27657122, ..., -0.9163003 ,
        -0.57850497, -0.57600312],
       [-0.43861408, -1.09499335,  1.63237987, ...,  0.93491535,
        -0.57850497,  1.73610172],
       [ 0.99095472, -1.09499335, -0.65836144, ..., -0.39389292,
         1.72859362, -0.57600312]])

In [0]:
model = Sequential()
model.add(Dense(X.shape[1],activation="relu",input_dim = X.shape[1] ))
model.add(Dense(128,activation="relu"))
#Crio com só 1 nó por que e uma saida binária e por esse mesmo motivo a sigmoid foi usada já que ela vai fazer a saída ser entre 0 e 1
model.add(Dense(1,activation="sigmoid"))

model.compile(optimizer="adam",loss = "binary_crossentropy", metrics=['accuracy'])

#Teve que converter por que a o X_train e um numpy.array() e ambas entradas tem que ser do mesmo tipo
model.fit(X_train,y_train.to_numpy(), batch_size=10, epochs = 10, verbose=1)

In [0]:
y_prev = model.predict(X_teste)
y_prev = np.argmax(y_prev, axis=-1)

In [0]:
y_prev

Out[28]: array([0, 0, 0, ..., 0, 0, 0])

In [0]:
model.evaluate(X_test,y_test.to_numpy())

63/63 [==============================] - 0s 1ms/step - loss: 0.3511 - accuracy: 0.8605
Out[29]: [0.3511064946651459, 0.8604999780654907]

In [0]:
from sklearn.metrics import confusion_matrix, accuracy_score

In [0]:
print(confusion_matrix(y_test.to_numpy(),y_prev))

[[1593    0]
 [ 407    0]]


In [0]:
accuracy_score(y_test.to_numpy(),y_prev)

Out[36]: 0.7965